name: prj
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.14
  - pip=25.1
  - openjdk=11.0.26         
  - grpcio>=1.60.0           
  - grpcio-tools>=1.60.0     
  - pandas>=2.2.3            
  - pyarrow>=15.0.0
  - python-snappy>=0.6.1
  - matplotlib>=3.10.0
  - sqlalchemy>=2.0.0
  - notebook>=6.5.4
  - ipykernel>=6.25.0
  - requests>=2.32.3
  - pip:
    # Data Engineering Frameworks (Better in Pip for plugin compatibility)
    - dbt-core==1.9.6
    - dbt-bigquery==1.9.2
    - dagster==1.9.13
    - dagster-dbt==0.25.13
    - dagster-duckdb==0.25.13
    - dagster-duckdb-pandas==0.25.13
    - dagster-meltano==1.5.5
    - dagster-webserver==1.9.13
    - meltano==3.7.8
    
    # Big Data & Storage
    - pyspark==3.5.1            
    - duckdb==1.3.0
    - duckdb-engine==0.15.0
    - google-cloud-storage==2.10.0
    - pymongo==4.4.1
    - redis==4.6.0
    - fastavro==1.8.2
    - google-cloud-bigquery
    
    # Utilities
    - great-expectations==1.4.1 
    - python-dotenv==1.1.0
    - thriftpy2==0.4.16
    - kaggle==1.5.13
    - seaborn
    - db-dtypes                  